"""add_flag_and_needs_review_to_ticket

Revision ID: cd647f44f7d5
Revises: 935310b909b6
Create Date: 2026-10-04 12:33:15.832832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd647f44f7d5'
down_revision: Union[str, Sequence[str], None] = '935310b909b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('flag', sa.String(length=50), nullable=True))
    op.add_column('ticket', sa.Column('needs_review', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'needs_review')
    op.drop_column('ticket', 'flag')
    # ### end Alembic commands ###
